server:
  port: 8082   # notification service ch?y khác port v?i payment service

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false   # false = Queue
