
jwt:
  ACCESS_TOKEN_SIGNER_KEY: "nOvg7u2rHldO+/Qc/BA6my5zQ9aKIGk5lw5/iVQ68Xx52YGn9DkTncKRUw9S3qtE"
  REFRESH_TOKEN_SIGNER_KEY: "dLfx3001G8bx3wEBOWgKgBb4HcfdkU/SFV+Bui6OhrO+WOvXkpt24mSFGhpNANdE"
  ACCESS_TOKEN_DURATION: 7200 # in second
  REFRESH_TOKEN_DURATION: 72000 # in second

mailersend:
  api:
    token: "mlsn.fe3360b60c86aa35dab2cf553368ba4de7dc662845cf8aa40928d309b51bcd80"
  from:
    email: "tuanhiepdev@test-51ndgwvnk25lzqx8.mlsender.net"
    name: "Proton Banking"