server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-init-sql: SELECT 1
      initialization-fail-timeout: 0
      data-source-properties:
        connectTimeout: 30000
        socketTimeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate   # Prod thường không auto tạo bảng
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  activemq:
    broker-url: tcp://banking-activemq:61616
    user: admin
    password: admin
    packages:
      trust-all: true

  jms:
    template:
      default-destination: bank-payment-queue

  data:
    redis:
      host: banking-redis
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_NAME_MAIL_SENDER}
    password: ${PASSWORD_MAIL_SENDER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  ACCESS_TOKEN_SIGNER_KEY: ${ACCESS_TOKEN_SIGNER_KEY}
  REFRESH_TOKEN_SIGNER_KEY: ${REFRESH_TOKEN_SIGNER_KEY}
  ACCESS_TOKEN_DURATION: 3600
  REFRESH_TOKEN_DURATION: 36000

mailersend:
  api:
    token: ${MAILERSEND_API_TOKEN}
  from:
    email: ${MAILERSEND_FROM_EMAIL}
    name: ${MAILERSEND_FROM_NAME}
